In [ ]:
import numpy as np

In [ ]:
distance_array = np.array([100, 200, 400, 800, 1500, 3000, 5000, 10000])
print(distance_array)

[  100   200   400   800  1500  3000  5000 10000]


In [ ]:
minimum = min(distance_array)
maximum = max(distance_array)
print(minimum, maximum)
print(minimum)
print(maximum)

100 10000
100
10000


In [ ]:
average_distance = np.mean(distance_array)
print(average_distance)

2625.0


In [ ]:
total_distance = np.sum(distance_array)
print(total_distance)

21000


In [ ]:
cumulative_sum = np.cumsum(distance_array)
print(cumulative_sum)

[  100   300   700  1500  3000  6000 11000 21000]


In [ ]:
round_all = np.round_(distance_array)
print(round_all)

[  100   200   400   800  1500  3000  5000 10000]
